### ISSUE TITLE
BİG SUR

### ISSUE THREAD

**Issue by bugraduz** [bdragonh/T480S-EFI#1]
I cant boot your efi with big sur.

**Comment by bdragonh** [comment]
10.16 is not supported,
You can try to upgrade the driver to the latest version.

**Comment by bugraduz** [comment]
which driver ?

**Comment by bdragonh** [comment]
I just updated the driver, you can download it again and try again.

**Comment by bugraduz** [comment]
yes ı can boot uptaded version but touchpad is not working. And my WiFi DW1820a not work

**Comment by bdragonh** [comment]
I don't want to upgrade bigsur,so you have to solve the remaining problems yourself.
